#!/data/data/com.termux/files/usr/bin/env python3
# SPDX-License-Identifier: 0BSD
"""Termux alarm clock."""

from argparse import ArgumentParser
from time import sleep, ctime, time
from random import choices, choice
from signal import SIGINT, signal
from string import punctuation
from subprocess import run
from pathlib import Path
from json import loads
from math import ceil
from sys import exit


class MusicPlayer:
    PLAYER_CMD = "termux-media-player"
    VOLUME_CMD = "termux-volume"
    STREAM = "music"

    def __init__(self) -> None:
        self.old_volume = 0
        self.half_volume = ceil(self.get_volume(find_max=True) / 2)

        path = Path.home() / "storage" / "downloads"
        self.test_file = path / "00-termux-alarm-clock"
        self.file = path / "alarm"

        self.test_file.mkdir()
        signal(SIGINT, self.check_then_stop)

    def play(self) -> None:
        self.save_volume()
        self.set_volume(self.half_volume)
        run([self.PLAYER_CMD, "play", self.file])

    def check_then_stop(self, signum: int = 0, frame: None = None) -> None:
        # Random KeyboardInterrupt protection
        if self.test_file.is_dir():
            return
        run([self.PLAYER_CMD, "stop"])
        self.set_volume(self.old_volume)
        run(["termux-wake-unlock"], check=True)
        exit(0)

    def stop(self) -> None:
        self.test_file.rmdir()
        self.check_then_stop()

    def set_volume(self, level: int) -> None:
        run([self.VOLUME_CMD, self.STREAM, str(level)])

    def get_volume(self, find_max: bool) -> int:
        prefix = "max_" if find_max else ""
        volume_data = run([self.VOLUME_CMD], capture_output=True, text=True)
        streams = loads(volume_data.stdout)
        for stream in streams:
            if stream["stream"] == self.STREAM:
                return stream[prefix + "volume"]
        return 0

    def save_volume(self) -> None:
        self.old_volume = self.get_volume(find_max=False)


music = MusicPlayer()


def vibrate(duration: int) -> None:
    music.check_then_stop()
    run(["termux-vibrate", "-f", "-d", str(duration)])


def vibrate_random(repeats: int) -> None:
    pattern = choices(range(100, 901, 200), k=repeats)
    for duration in pattern:
        vibrate(duration)
        sleep(duration/1000 + 0.2)


def notify(minutes: int, seconds: int) -> None:
    run(["clear"], check=True)
    run(["termux-toast", str(minutes)], check=True)
    repeats = 12 if minutes > 99 else 16
    for _ in range(repeats):
        print(f"{choice(punctuation)}{minutes}"*repeats)
        print(f"{minutes}{choice(punctuation)}"*repeats)
    print("\nThe alarm is set on", ctime())
    print("Wake up on", ctime(time() + seconds), "\n")


def alarm(silent: bool) -> None:
    print("Remove", music.test_file)
    vibrate_random(64)
    if not silent:
        music.play()
    vibrate_random(64)


def wait_for_alarm(minutes: int) -> None:
    run(["termux-wake-lock"], check=True)
    seconds = minutes*60
    notify(minutes, seconds)
    sleep(seconds)


def main() -> None:
    parser = ArgumentParser(
        description="Termux alarm clock, requires termux-api"
    )
    parser.add_argument(
        "-s", "--silent", action="store_true", help="Do not play music"
    )
    args = parser.parse_args()
    if not music.file.exists():
        raise FileNotFoundError(f"Place your music file at {music.file}")

    minutes = int(input("How many minutes until the alarm "))
    if minutes < 0:
        raise ValueError
    wait_for_alarm(minutes)
    alarm(silent=args.silent)
    print("Ended")
    music.stop()


if __name__ == "__main__":
    main()
